### ISSUE TITLE
Improve end screen

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#55] opened 2020-04-15 17:26 UTC
After first release.

I think we could add the smiley pictures to the stats in the end screen.
This way we would also visually demonstrate the meaning of the numbers.
Example:

Exposed:                 57[Pic of the exposed smiley]

**Comment by holke** [comment] 2020-04-21 11:40
We should remove the "Beenden" Button. On the website it does end the game, but the game cannot be started again, except when pressing F5.
And as we discussed before, it was more meant for debugging than gameplay.

**Comment by holke** [comment] 2020-04-21 11:43
Should we have a different end screen if the player dies?
Like a message "game over"...mhmm but maybe this is more related to #61

**Comment by holke** [comment] 2020-04-21 20:10
@FredyHennig @maccxs : I tried adding pictures of the smileys to the end screen.
What i did was pulling the sprite into the Scene Hirarchy which created a new image of the smiley.
However, it is rendered behind the UI, so that it is not visible.
Before i dive deeper into sorting layers and all that (which after 1 hour of search seems like a hell pit), did you have this problem before and know a solution?

**Comment by maccxs** [comment] 2020-04-22 06:22
Hi, sorry I have no idea what the problem is :-(

**Comment by maccxs** [comment] 2020-04-22 06:28
@holke found a workaround or fix? Look at the Canvas of the endscreen, where @FredyHennig separated the virae from the background, do it like that. Create new empty game object in the canvas, set component Image, give it the sprite and it worked for me like that.

**Comment by holke** [comment] 2020-04-22 12:35
That worked like a charm, thank you :)

**Comment by maccxs** [comment] 2020-04-27 14:36
Can I merge your 2fdb3ffdc5fca0c7ccaad38eec771322454847a3 and close this

**Comment by holke** [comment] 2020-04-27 14:53
yes you can

**Closed as completed** 2020-04-27 16:08 UTC
